apiVersion: v1
kind: Service
metadata:
  labels:
    app: shilpa
  name: shilpa-deployment
  namespace: shilpa-ns
spec:
  ports:
  - nodePort: 30853
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: shilpa
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}